FROM mcr.microsoft.com/dotnet/aspnet:8.0.4-alpine3.19 as base
WORKDIR /app
# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:8.0.204 as build

RUN dotnet nuget add source "https://nuget.cdn.azure.cn/v3/index.json" -n "azure.cn"

COPY ./SiloHost/SiloHost.csproj /src/SiloHost/SiloHost.csproj
COPY ./Grains/Grains.csproj /src/Grains/Grains.csproj
COPY ./Interfaces/Interfaces.csproj /src/Interfaces/Interfaces.csproj
COPY ./Client/Client.csproj /src/Client/Client.csproj
RUN dotnet restore "/src/SiloHost/SiloHost.csproj"
RUN dotnet restore "/src/Client/Client.csproj"

COPY ./SiloHost/src/* /src/SiloHost/src/
COPY ./Grains/src/* /src/Grains/src/
COPY ./Interfaces/src/* /src/Interfaces/src/
COPY ./Client/src/* /src/Client/
RUN dotnet build "/src/SiloHost/SiloHost.csproj" -c Release
RUN dotnet build "/src/Client/Client.csproj" -c Release

FROM build AS publish
RUN dotnet publish --verbosity normal "/src/Client/Client.csproj" -c Release -o /app/publish
COPY ./ops/entrypoint.sh /app/publish/

FROM base AS final
COPY --from=publish /app/publish ./
EXPOSE 3000
EXPOSE 8080
CMD ["dotnet", "Client.dll"]
ENTRYPOINT ["./entrypoint.sh"]
