version: "3"

networks:
  hostnet:

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    networks:
      - hostnet
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  silo-host:
    image: silo-host
    links:
      - datadog-agent
    networks:
      - hostnet
    ports:
      - ${DASHBOARDPORT}:${DASHBOARDPORT}
      - ${GATEWAYPORT}:${GATEWAYPORT}
    environment:
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - DD_INTEGRATIONS=/opt/datadog/integrations.json
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_AGENT_HOST=datadog-agent
      - DD_VERSION=1.0
      - DD_SERVICE=${DATADOG_SERVICE_NAME}
      - DD_ENV=${DATADOG_ENVIRONMENT}
      - ADVERTISEDIP=${ADVERTISEDIP}
      - GATEWAYPORT=${GATEWAYPORT}
      - DASHBOARDPORT=${DASHBOARDPORT}