@UrlShortener_HostAddress = https://localhost:7039

###
GET {{UrlShortener_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{UrlShortener_HostAddress}}/weatherforecast/shorten?url=http://www
Accept: application/json

### 200
GET {{UrlShortener_HostAddress}}/weatherforecast/getlong?shortUrl=31DCD6B9
Accept: application/json

### 404
GET {{UrlShortener_HostAddress}}/weatherforecast/getlong?shortUrl=31DCD6B91
Accept: application/json

### 
GET {{UrlShortener_HostAddress}}/weatherforecast/GrainGet?shortUrl=31DCD6B91
Accept: application/json

### 
POST {{UrlShortener_HostAddress}}/weatherforecast/GrainSet
Accept: application/json
